apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kafka
  name: kafka
  namespace: kafka
spec:
  ports:
  - port: 9092
    nodePort: 30042
    protocol: TCP
    targetPort: 9092
  selector:
    app: kafka
  type: NodePort
status:
  loadBalancer: {}
