apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zookeeper-pvc
  namespace: kafka
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gce-storage-class
  resources:
    requests:
      storage: 5Gi
